# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd2503ba404941088abb01d0072f3b8db66d0d45e738c794fed5126254f8b243c7f91aa1c6ba7bb652074d8eae9c2a2fea252a809deb71a6f65e35bb72a17b4b

test:
  secret_key_base: 38e6a6bf200f757a83f4d12767907faab06fdd78d13346f4e70f76e9cff28f0047a05867240cb88ecb893eb8a58610cbf992290edf2573ee64cbdd929751ca38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
